version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose the frontend port to Nginx

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Expose the backend port to Nginx
    environment:
      - NODE_ENV=production